<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-A766M3G" failures="0" tests="1" name="MainPackage.ExceptionTimeoutTest" time="5.037" errors="1" timestamp="04 Jul 2020 06:45:29 GMT" skipped="0">
  <testcase classname="MainPackage.ExceptionTimeoutTest" name="infinitelooptest" time="5.037">
    <error message="Method MainPackage.ExceptionTimeoutTest.infinitelooptest() didn&#039;t finish within the time-out 5000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method MainPackage.ExceptionTimeoutTest.infinitelooptest() didn't finish within the time-out 5000at java.base@9.0.1/java.io.Writer.write(Unknown Source)at java.base@9.0.1/java.io.BufferedWriter.newLine(Unknown Source)at java.base@9.0.1/java.io.PrintStream.newLine(Unknown Source)at java.base@9.0.1/java.io.PrintStream.println(Unknown Source)at app//MainPackage.ExceptionTimeoutTest.infinitelooptest(ExceptionTimeoutTest.java:11)at java.base@9.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base@9.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at java.base@9.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.base@9.0.1/java.lang.reflect.Method.invoke(Unknown Source)at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:40)at java.base@9.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)at java.base@9.0.1/java.util.concurrent.FutureTask.run(Unknown Source)at java.base@9.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)at java.base@9.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)at java.base@9.0.1/java.lang.Thread.run(Unknown Source)]]>
    </error>
  </testcase> <!-- infinitelooptest -->
</testsuite> <!-- MainPackage.ExceptionTimeoutTest -->
